# Generated by Django 4.2.16 on 2026-05-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_image_url_and_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentlisting',
            name='condition',
            field=models.CharField(blank=True, help_text='e.g. New, Used, Refurbished', max_length=50),
        ),
    ]
