# Generated by Django 5.0.6 on 2026-05-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_equipmentlisting_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='static_image',
            field=models.CharField(blank=True, help_text="Image filename in static/core/equipment_images/ (e.g. 'drill.jpg')", max_length=255),
        ),
    ]
