# Generated by Django 5.0.6 on 2026-07-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='manual_active_rentals',
            field=models.IntegerField(default=0, help_text='Admin adjustment to active rentals count'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manual_total_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Admin adjustment to total spent amount', max_digits=15),
        ),
    ]
